package com.habitguard.app.model

data class AppUsageItem(
    val packageName: String,
    val appName: String,
    val minutes: Long,
    val lastTimeUsed: Long,
    val openCount: Int = 0,
    val firstOpenTime: Long = 0,
    val nightMinutes: Long = 0,
    val sessionCount: Int = 0,
    val averageSessionMinutes: Long = 0,
    val maxSessionMinutes: Long = 0,
    val category: String = "\uAE30\uD0C0",
)

data class ParsedGoal(
    val targetName: String,
    val targetPackage: String,
    val timeRange: String,
    val limitMinutes: Int,
    val intensity: String,
    val missionType: String,
    val rawText: String = "",
    val targetCategory: String = "\uAE30\uD0C0",
    val confidenceScore: Int = 50,
    val confidenceReasons: List<String> = emptyList(),
    val needsUserConfirmation: Boolean = confidenceScore < 70,
)

data class RestrictionRule(
    val targetPackage: String,
    val targetName: String,
    val limitMinutes: Int,
    val startHour: Int,
    val endHour: Int,
    val restrictionMode: String,
    val missionType: String,
    val unlockMinutes: Int,
    val enabled: Boolean,
)

data class GuardDebugEvent(
    val packageName: String,
    val eventType: String,
    val blocked: Boolean,
    val unlockTokenValid: Boolean,
    val missionResult: String,
    val createdAt: Long,
)

data class DailyUsageSummary(
    val date: String,
    val totalMinutes: Long,
    val topAppName: String,
    val topAppMinutes: Long,
    val nightMinutes: Long = 0,
    val sessionCount: Int = 0,
    val averageSessionMinutes: Long = 0,
    val maxSessionMinutes: Long = 0,
    val dataQuality: String = "UNKNOWN_ERROR",
)

data class HourlyUsageItem(
    val hour: Int,
    val minutes: Long,
)

data class DashboardState(
    val totalMinutes: Long = 0,
    val nightMinutes: Long = 0,
    val openCount: Int = 0,
    val notificationCount: Int = 0,
    val hasUsageAccess: Boolean = false,
    val hasAccessibilityAccess: Boolean = false,
    val hasNotificationAccess: Boolean = false,
    val riskLabel: String = "\uB0AE\uC74C",
    val habitType: String = "\uADE0\uD615 \uAD00\uB9AC\uD615",
    val habitTypeDescription: String = "",
    val healthScore: Int = 100,
    val missionAttempts7d: Int = 0,
    val missionSuccessRate7d: Int = 0,
    val missionFailures7d: Int = 0,
    val hasActiveGoal: Boolean = false,
    val goalAchievedToday: Boolean = false,
    val goalProgressText: String = "",
    val appUsage: List<AppUsageItem> = emptyList(),
    val dailySummaries: List<DailyUsageSummary> = emptyList(),
    val hourlyUsage: List<HourlyUsageItem> = emptyList(),
    val riskWindowText: String = "",
    val weeklyBaselineAverage: Long = 0,
    val weeklyWithRuleAverage: Long = 0,
    val weeklySavedMinutes: Long = 0,
    val collectedCompleteDays: Int = 0,
    val recent7DayAverage: Long = 0,
    val personalBaselineMinutes: Long = 0,
    val dataReadinessMessage: String = "",
    val personalizedPredictionReady: Boolean = false,
    val aiPredictedTomorrowMinutes: Long = 0,
    val aiPredictionDisplayText: String = "",
    val aiPredictionSourceLabel: String = "",
    val aiPredictionModelVersion: String = "",
    val aiPredictionCalculatedAtText: String = "",
    val aiPredictionDataQualityStatus: String = "",
    val aiPredictionSourceType: String = "",
    val aiPredictionEvaluationScope: String = "",
    val aiGoalRiskText: String = "",
    val aiRecommendationText: String = "",
    val aiModelSummary: String = "",
    val aiModelPerformance: String = "",
    val aiModelTopFeatures: String = "",
    val aiModelCaveat: String = "",
    val predictionReasons: List<String> = emptyList(),
    val insights: List<String> = emptyList(),
    val activeGoalText: String = "",
    val latestPredictionText: String = "",
    val activeRule: RestrictionRule? = null,
    val guardDebugEvents: List<GuardDebugEvent> = emptyList(),
    val firestoreSyncEnabled: Boolean = false,
    val firestoreSyncStatus: String = "",
)
